services:

  db:
    image: postgres
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: zG?NB6vf
      POSTGRES_USER: nest_app_user
    volumes:
     - data:/var/lib/postgresql/data
    networks:
     - app-network

volumes:
  data:

networks:
  app-network: